# Rnn project

In [2]:
from tensorflow.keras.preprocessing.text  import one_hot


In [3]:
sentences = [
    "The sun is bright.",
    "I like tea.",
    "She is happy.",
    "Dogs can run.",
    "It is cold.",
    "We are ready.",
    "He reads books.",
    "The sky is blue.",
    "Time goes fast.",
    "Birds can fly.",
    "I see you.",
    "Please sit down.",
    "The door is open.",
    "This is easy.",
    "She sings well.",
    "The baby sleeps.",
    "Water is clear.",
    "I found it.",
    "The cat jumps.",
    "We love music."
]


In [4]:
## we need to define vocablary size

In [6]:
voc_size = 10000

In [13]:
ohe_rep = [one_hot(words,voc_size)for words in sentences]
ohe_rep

[[3696, 1909, 4709, 9146],
 [5362, 5519, 6160],
 [1794, 4709, 4376],
 [7766, 826, 8170],
 [8567, 4709, 3805],
 [9044, 8040, 8648],
 [3887, 2081, 6845],
 [3696, 4861, 4709, 7999],
 [8321, 8002, 8339],
 [9106, 826, 4239],
 [5362, 2013, 1870],
 [472, 2552, 22],
 [3696, 7973, 4709, 9067],
 [5573, 4709, 3771],
 [1794, 936, 8156],
 [3696, 5249, 2616],
 [5572, 4709, 2788],
 [5362, 8801, 8567],
 [3696, 9372, 9628],
 [9044, 6953, 4367]]

## sentences words is got converted in vector with in the 10000 vocabllary

# Our each words got an index in the vocablery size out of 1000 like show in above list of vectors

## now we have a option to rduce the dim use our pca(principle components analyis)

# word embeding layers

## We pass our index vector to the embeding layers

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [27]:
sentences_len = 7
embedded_docs = pad_sequences(ohe_rep,padding='pre',maxlen=sentences_len)
embedded_docs

array([[   0,    0,    0, 3696, 1909, 4709, 9146],
       [   0,    0,    0,    0, 5362, 5519, 6160],
       [   0,    0,    0,    0, 1794, 4709, 4376],
       [   0,    0,    0,    0, 7766,  826, 8170],
       [   0,    0,    0,    0, 8567, 4709, 3805],
       [   0,    0,    0,    0, 9044, 8040, 8648],
       [   0,    0,    0,    0, 3887, 2081, 6845],
       [   0,    0,    0, 3696, 4861, 4709, 7999],
       [   0,    0,    0,    0, 8321, 8002, 8339],
       [   0,    0,    0,    0, 9106,  826, 4239],
       [   0,    0,    0,    0, 5362, 2013, 1870],
       [   0,    0,    0,    0,  472, 2552,   22],
       [   0,    0,    0, 3696, 7973, 4709, 9067],
       [   0,    0,    0,    0, 5573, 4709, 3771],
       [   0,    0,    0,    0, 1794,  936, 8156],
       [   0,    0,    0,    0, 3696, 5249, 2616],
       [   0,    0,    0,    0, 5572, 4709, 2788],
       [   0,    0,    0,    0, 5362, 8801, 8567],
       [   0,    0,    0,    0, 3696, 9372, 9628],
       [   0,    0,    0,    0,

In [28]:
# feature representation
dim = 10

In [29]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sentences_len,)))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 7, 10)          │       100,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 7, 1)           │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,011 (390.67 KB)

 Trainable params: 100,011 (390.67 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
embedded_docs[0]

array([   0,    0,    0, 3696, 1909, 4709, 9146], dtype=int32)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step


array([[[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.04131579],
        [ 0.06269657],
        [-0.00681649],
        [ 0.01459784]],

       [[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.02037915],
        [-0.01832363],
        [ 0.00395462]],

       [[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.01626327],
        [-0.00681649],
        [-0.03596599]],

       [[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [-0.03249818],
        [-0.00123656],
        [ 0.03094539]],

       [[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [-0.01085422],
        [-0.00681649],
        [ 0.0233278 ]],

       [[ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [ 0.03431453],
        [-0.01000137],
        [-0.05720561],
        [ 0.01509521]],

       [[ 0.03431453],

In [33]:
## hey this is how our embeding layers work